name: CD

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create SERVICE_ACCOUNT.json
        run: 'echo "$SERVICE_ACCOUNT" > SERVICE_ACCOUNT.json'
        shell: bash
        env:
          SERVICE_ACCOUNT: ${{secrets.SERVICE_ACCOUNT}}

      - name: Heroku Build and Deploy
        uses: akhileshns/heroku-deploy@v3.10.9
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "shielded-ravine-12027"
          heroku_email: "bamf.rabin@gmail.com"
