name: CD

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create SERVICE_ACCOUNT.json
        run: 'echo "$SERVICE_ACCOUNT" > SERVICE_ACCOUNT.json'
        shell: bash
        env:
          SERVICE_ACCOUNT: ${{secrets.SERVICE_ACCOUNT}}

      # Setup gcloud CLI
      - uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.SERVICE_ACCOUNT }}
          project_id: shorten-s
          export_default_credentials: true
      
      - name: gcloud info
        run: gcloud info

