name: CD

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create SERVICE_ACCOUNT.json
        run: 'echo "$SERVICE_ACCOUNT" > SERVICE_ACCOUNT.json'
        shell: bash
        env:
          SERVICE_ACCOUNT: ${{secrets.SERVICE_ACCOUNT}}

      - name: Setup Gcloud CLI
        uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.SERVICE_ACCOUNT }}
          project_id: shorten-s
          export_default_credentials: true
      
#      - name: Auth Service Account
#        run: gcloud auth activate-service-account --key-file=${{ secrets.SERVICE_ACCOUNT }}

      - name: Configure Docker
        run: gcloud auth configure-docker

      - name: Build Image
        run: docker build -t gcr.io/shorten-s/shorten-test .

      - name: Push Image to GCR
        run: docker push gcr.io/shorten-s/shorten-test
      
      