name: CD

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create SERVICE_ACCOUNT.json
        run: 'echo "$SERVICE_ACCOUNT" > SERVICE_ACCOUNT.json'
        shell: bash
        env:
          SERVICE_ACCOUNT: ${{secrets.SERVICE_ACCOUNT}}

      - name: Heroku Login
        run: heroku login
        env:
          HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}

      - name: Heroku deploy
        run: git push heroku main
        env:
          HEROKU_APP: shielded-ravine-12027
