name: CD

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create SERVICE_ACCOUNT.json
        run: 'echo "$SERVICE_ACCOUNT" > SERVICE_ACCOUNT.json'
        shell: bash
        env:
          SERVICE_ACCOUNT: ${{secrets.SERVICE_ACCOUNT}}


      - uses: RafikFarhad/push-to-gcr-github-action@v3.0.2
        with:
          gcloud_service_key: ${{ secrets.SERVICE_ACCOUNT }}
          registry: gcr.io
          project_id: shorten-s
          image_name: shorten-image-test

