name: CI

on:
  push:
    branches:
      - main
  pull_request_target:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2

      # Creates service account for firebase
      - name: Create SERVICE_ACCOUNT.json
        run: 'echo "$SERVICE_ACCOUNT" > SERVICE_ACCOUNT.json'
        shell: bash
        env:
          SERVICE_ACCOUNT: ${{secrets.SERVICE_ACCOUNT}}
        
      - name: Setup Node
        uses: actions/setup-node@v2.1.4

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build

      # Run unit tests
      - name: Test
        run: npm run test
